### ISSUE TITLE
OAuth2 based SSO implementation

### ISSUE THREAD

**Issue by jlachowski** [coriolinus/oauth2-article#4]
Hi, 

I've read your article and I was wondering if you would be able/willing to implement an OAuth2/OpenID based SSO for a django/python web application. 
How can I contact you directly (email?) to talk about the issue, rates etc.?

Regards
Jarosław

**Comment by coriolinus** [comment]
Sent you an email at j...i@w...s.com. Let's continue this conversation via that channel.
